apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: infra
    app.kubernetes.io/part-of: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://github.com/mathisDlmr/k3s-project.git
      targetRevision: main
      ref: k3s-project
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.21.0
      helm:
        valueFiles:
          - $k3s-project/kubernetes/valueFiles/cert-manager.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
