apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: infra
    app.kubernetes.io/part-of: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://github.com/mathisDlmr/k3s-project.git
      targetRevision: main
      ref: k3s-project
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.19.1
      helm:
        valueFiles:
          - $k3s-project/kubernetes/valueFiles/cilium.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
