apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-ingress
  namespace: infra
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  rules:
  - host: registry.mdlmr.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry
            port:
              number: 5000
  - host: skiut.mdlmr.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: skiut
            port:
              number: 80
  - host: hosting.mdlmr.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hosting
            port:
              number: 80
  - host: argocd.mdlmr.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
  - host: mdlmr.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website
            port:
              number: 80

  tls:
  - hosts:
    - registry.mdlmr.fr
    - skiut.mdlmr.fr
    - hosting.mdlmr.fr
    - argocd.mdlmr.fr
    - mdlmr.fr
    secretName: mdlmr-fr-tls