apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: monitoring
    app.kubernetes.io/part-of: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  sources:
    - repoURL: https://github.com/mathisDlmr/k3s-project.git
      targetRevision: main
      ref: k3s-project
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.24.4
      helm:
        valueFiles:
          - $k3s-project/kubernetes/valueFiles/tempo.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
