apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: k3s-controller-manager
  namespace: monitoring
spec:
  jobName: k3s-controller-manager
  scheme: https
  authorization:
    credentials:
      name: kube-prometheus-stack-prometheus-token
      key: token
  tlsConfig:
    insecureSkipVerify: true
    ca:
      configMap:
        name: kube-root-ca.crt
        key: ca.crt
  staticConfigs:
    - targets:
        - '100.112.35.79:10257'
        - '100.126.60.86:10257'
        - '100.113.113.100:10257'
