# That token will be used by ScrapeConfig to authenticate to Kubernetes API
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-prometheus-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: kube-prometheus-stack-prometheus
type: kubernetes.io/service-account-token
