apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: skiut-database
  namespace: skiut
spec:
  serviceName: skiut-database
  replicas: 1
  selector:
    matchLabels:
      app: skiut-database
  template:
    metadata:
      labels:
        app: skiut-database
    spec:
      containers:
        - name: skiut-database
          image: mysql:8.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init-scripts
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: skiut-database-configmap
                  key: MYSQL_DB
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skiut-database-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: skiut-database-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skiut-database-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
      volumes:
        - name: mysql-init-scripts
          configMap:
            name: skiut-database-init
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 10Gi
