apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: skiut-backend
  namespace: skiut
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: skiut-backend-secret
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /skiut/backend
        name:
          regexp: ".*"
