apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: meta
  labels:
    app.kubernetes.io/part-of: k3s-project
  annotations:
    description: "Application infra - S'occupe de l'infra transversale (traefik, cert-manager, monitoring, metrics, etc.)"
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  source:
    repoURL: 'https://github.com/mathisDlmr/k3s-project.git'
    targetRevision: main
    path: infra/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
