apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hosting
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: k3s-project
  annotations:
    description: "Application hosting - S'occupe de l'hébergement (Sites statiques et apps dockerisées)"
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: hosting
  source:
    repoURL: 'https://github.com/mathisDlmr/k3s-project.git'
    targetRevision: main
    path: apps/hosting/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
