apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pic
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: pic
    app.kubernetes.io/part-of: meta
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: pic
  source:
    repoURL: https://github.com/mathisDlmr/k3s-project.git
    targetRevision: main
    path: apps/pic-p26/
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
