apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: k3s-project
  annotations:
    description: "Application infra - S'occupe de l'infra transversale (traefik, cert-manager, monitoring, metrics, etc.)"
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: "https://github.com/mathisDlmr/k3s-project.git"
    targetRevision: main
    path: infra/
    git:
      submoduleEnabled: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
