apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sr05-app
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: meta
    app.kubernetes.io/part-of: meta
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: werewolf
  sources:
    - repoURL: https://github.com/mathisdlmr/sr05-projet.git
      targetRevision: main
      path: k8s/
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
