apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: infra
    app.kubernetes.io/part-of: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://github.com/mathisDlmr/k3s-project.git
      targetRevision: main
      path: infra/longhorn
    - repoURL: https://github.com/mathisDlmr/k3s-project.git
      targetRevision: main
      ref: k3s-project
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.12.0
      helm:
        valueFiles:
          - $k3s-project/valueFiles/longhorn.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
