apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: monitoring-v2
    app.kubernetes.io/part-of: monitoring-v2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  sources:
    - repoURL: https://github.com/mathisDlmr/k3s-project.git
      targetRevision: main
      ref: k3s-project
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-metrics-single
      targetRevision: 0.42.0
      helm:
        valueFiles:
          - $k3s-project/valueFiles/victoria-metrics.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-v2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
