apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: "77.11.1"
    helm:
      values: |
        crds:
          enabled: false   # CRDs gérés séparément par prometheus-crds app
        prometheus:
          serviceAccount:
            create: true
            name: monitoring-stack-kube-prom-prometheus
          prometheusSpec:
            replicas: 1
            scrapeInterval: 30s
            evaluationInterval: 30s
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            ruleSelector: {}
            ruleNamespaceSelector: {}
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  resources:
                    requests:
                      storage: 20Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
