apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook-external-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: alertmanager-slack-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: webhook-critical
      remoteRef:
        key: /monitoring/ALERTMANAGER_SLACK_WEBHOOK_CRITICAL
    - secretKey: webhook-warning
      remoteRef:
        key: /monitoring/ALERTMANAGER_SLACK_WEBHOOK_WARNING
