apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-slack-config
  namespace: monitoring
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ["job"]
    receiver: "slack"
  receivers:
    - name: "slack"
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-webhook-secret
            key: webhook
          channel: "#alerts"
