apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-slack-config
  namespace: monitoring
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ["job"]
    receiver: "slack-warning"
    routes:
      - matchers:
          - name: severity
            value: critical
            matchType: "="
        receiver: "slack-critical"
  receivers:
    - name: "slack-critical"
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-webhook-secret
            key: webhook-critical
          channel: "#alerts-critical"
    - name: "slack-warning"
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-webhook-secret
            key: webhook-warning
          channel: "#alerts-warning"
