# roles/common/tasks/audit.yml
# Final verifications and run Lynis if enabled

---
- name: List opened ports
  ansible.builtin.command: ss -tulnp
  register: common_open_ports
  changed_when: false

- name: Firewall status
  ansible.builtin.command: ufw status verbose
  register: common_ufw_status
  changed_when: false

- name: Security summary of the node
  ansible.builtin.debug:
    msg: "{{ (common_open_ports.stdout_lines + [''] + common_ufw_status.stdout_lines) }}"

- name: Lynis audit
  ansible.builtin.command: lynis audit system --quick
  register: common_lynis
  changed_when: false
  when: run_lynis_audit | bool
  tags: [audit]

- name: Lynis report
  ansible.builtin.debug:
    msg: "{{ common_lynis.stdout_lines }}"
  when: run_lynis_audit | bool
  tags: [audit]
