# roles/common/tasks/firewall.yml
# Define UFW rules

- name: Default policy - deny incoming
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Default policy - allow outgoing
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow Tailscale WireGuard (41641/udp)
  community.general.ufw:
    rule: allow
    port: "41641"
    proto: udp

- name: Allow incoming from tailscale0
  community.general.ufw:
    rule: allow
    direction: in
    interface: tailscale0

- name: Allow local LAN
  community.general.ufw:
    rule: allow
    from_ip: "{{ lan_cidr }}"

- name: Allow from Cilium to host
  community.general.ufw:
    rule: allow
    from_ip: "{{ pod_cidr }}"

- name: Allow SSH from Tailscale
  community.general.ufw:
    rule: allow
    direction: in
    interface: tailscale0
    port: "22"
    proto: tcp

- name: Allow SSH from local LAN
  community.general.ufw:
    rule: allow
    from_ip: "{{ lan_cidr }}"
    port: "22"
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled
