apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: infra
spec:
  project: default
  source:
    repoURL: "https://github.com/mathisDlmr/k3s-project.git"
    targetRevision: main
    path: infra/cert-manager/cluster-issuer/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
