apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # Staging : https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
