# inventory/hosts.yml
# The first node declared will be the init node (cluster-init etcd), the others will join the cluster in order.

all:
  children:
    control_planes:
      hosts:
        5700u:
          ansible_host: 192.168.1.10
        5825u:
          ansible_host: 192.168.1.11
        n150:
          ansible_host: 192.168.1.12