apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: efk-es-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: efk-es-credentials
    creationPolicy: Owner
  data:
    - secretKey: kibana_username
      remoteRef:
        key: /monitoring/elasticsearch/KIBANA_USERNAME
    - secretKey: kibana_password
      remoteRef:
        key: /monitoring/elasticsearch/KIBANA_PASSWORD
    - secretKey: fluentbit_username
      remoteRef:
        key: /monitoring/elasticsearch/FLUENTBIT_USERNAME
    - secretKey: fluentbit_password
      remoteRef:
        key: /monitoring/elasticsearch/FLUENTBIT_PASSWORD
