apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine
  namespace: affine
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: affine-secret
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /affine/database
        name:
          regexp: ".*"
