---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCni0mDRnawRo1hJGXDUlXyP5xqrrNyUhAwsXD1Q8xUPJpuMNQt3/RFne6cCsBIhCAp85pjd7gPFfTGLoRXanbiMoULyHSIs5MAb+JXv6riDm18/V7wN2jh8ZdlrXRNIGgWBcl/HGtbRkIUDA7Q9HNb492ccaVxnFSalUzZJyKBusf9hKVv+wAt+CfEGqjvRkGF64qQa0LWU6NoEcOSaaU3CTVXU2Qj9/AvOAunOXGJGzlr4IuxReQ9RnS7Ku8ASJJotO+OSM+rgorhRWvrWSjz8wYxZ6DEKF7TzrUojPQIryZhKuutMSi0SUDW5iGFDSZI+B/u8hbORIxj2fmKWfPC3Tr83jHkC8xMDZ5+Oy4fDfjcsvuqbQAqU5ZyupLfWQX8v57eveAJnPu1lbqLEfFMbYnpb3EcvCXDZA3tk3jdrG7P+coTfZfIyqkhurRunQJNPo1NMHBXXRMHuBfWWlj40VFqBoDYi1Q7tRdBNQqlT0ZHLAi4LjwLiequ0MfpTJUeNKiCXfGxTSaWlaANzAluMHsxfj30Ybvy+Xc3ebnIkyZZpWvg7z+rOW3kMBczHVE9RnBnnf2h4ulbNVSztRDqTF5xOYzTvZlRYtu0XiQsk/XcGxS+wn+EZOepBu4TYb2APdh/xue6h0UPdvTwdXX/y2Y2wg6u6LOXAtj13fZAGEKQ6yhjCHbzFtf/Z4JnMwygbGLKmvQZTnJuVI99Ael61UhZ3BY=
    admin-user: AgBGm7suQoAUBD7K67/izBCTIQIbRArps174bQRG1sxBGJPCdjIGHzH3L046vE3rTDaxWAUm5JPZQyHdqHgktMBqqWD55xmfM+Nqx7fkOPYjf0uplP+ktk8RB723EKVCmE/fwCAp5phVE+kRwhDyMs8MFdkuX7Ua4WjPpbxwMiubUa9EsG2waXNr4CI4Ykhp6qR55AHlUz3DfcM/UkWxYE5MG1ep8EN+GiUzy69Hduu8SX6KZhPUoRkAD1fxU9c+/Fgnh0gHd4GjOyvcFujjCHFJfmBO0STQUQLF6hdh6eCY2gEHFJKIOZ3EJJ8jkbAEjgbwa9p4K6/caZUoWpu4IzxbHp1jXft8Tbxob5KH72kjWjBMTorHWiOQJBNAyEgBoMjklC9ecIdM3rxPpBrAaqpS+zP2xsi9Z6QrfcTmuIW2QL4EEHibjwF4tXl/ZxbS6laPBd3cQuvGTcPGgeP3d5dbzFTHtZx/uvGJdUUItxJrFoEutS7Hw6kf1DjjVjkGLMx8z5AFa0VXu5bOGK7sCQqOsK8VX/8SerNdkYO9CU7xt2ThhmNvrm4IQ4n/aul+M0ymla3ZuYE2iRoo7wYJPu4GKvu9WConkX2BbV2NdscdAwqdqNHHrvsOu57tMvzo/hgh+wpbD7cMnwpLLu6y2+3dV1x8y5VUXMkWEyLNg2FuyqreP3SzUlLp/CO7X9eTRAw4nrPg36M=
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
