---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCiorB110B8byh6c3E1aW5UZN6ITyzWMqkml1aO4C6OHyt/Ykcnfe9RglYlBDr+0puimicA1BKbS9CGlO9Na+AEmMpSe99EyfAyOqiQNPm+euky1BD2O+iY1FtiNke33yA8Ox/yLNuJwo9okNXhahI5U1iKFYA81k9h5XAgowBh9b2oVK83RMlgYGztM+IoD/oierm5q+yp5ce1JLUwvKYjQOtI6tBGQjTAYRDe7ZcqKmbiROiVrWcTyhb7dm4HYGnXQPrTNgf1Hze3qB7BGuuBpcKcf43a5qqvfobEnMfKD4hCKLm0rCL9UxIzaFS2GjRfMUKGBDzWwhz3LYINANdpJOqSbZC4eqowenfR0I3mh/vXGJqBmYVm074UNMk/E5LxCfqlc8kk7dG6nKylOlJ5vK1qip87/LZ/VAnDE4toRQKj8MOAIoZa0NOkFXPrH9LtWP392ylDjxyirzKpcdTyP6ix5uO9e4u2/H308uQVvNTeaKAzPYsrqOlN26yMf7ZhOb+cw77+VcICEIn4/3NY+x0WB1Jm27lsXZUfeaOBvoiS+sFmZs50v50qYM2NSmxoclWCEhh7skbEPqLwPxVHjN7BPz/M7K1/6ZQy+nki5XpLlie71k2dpx6AAviNoBVQNMW6eUYOmDYmzhoq6Saq8NqMiiAGgjb7BWgkxwbe76hzfy5/wwHB7IJMpu09/M42txJMbIsQOUj/rYEIXFl6L3tm/g==
    admin-user: AgBoip8J+WcLgLYT8yUbsmVuyfoDo2blz/mLARLdRIiORuTAinv7GoxmgDCQc6BBNrZbIuPDM/LSOP3GO4GkJlH/lxH1IXlxTrrzVG8l2b5qSpwzs8z6EXBgSNrj0BVVcXMLGlMeyldx/drvhJ9iT9qbw0V9QNKvoEXZfGbYVuuzfxkLepZBJZJAlZ36fFYGeDnKGwKXU6RgwFbsSpFZgPgA7HRTHviU1FFWeNtD0CrX5IQsC6d/IQZdXMOpVpfMlGwmumyG9ep64OGRZ4mHRuJYGLo0Ba0W1yZecKvLfaJrEjaHTKVRQTsofxj8+8AiK/V3E3ML7Pe+1LAhgArosdhEHRbR0PlHngo+/mGjXGCLCEmhsusyJ5wfDUPdmNaBLs0nuiKi/OxtPFpxlrBOuS9NSIpG2z5NIdQp2VqkpplklUpzyvHU07qWIRA89cw9JN0Qj92Ca/OG0xKYVwbiEagb6uAIBMbncBsHt8J8QEL9L33a3+5FJpKhCawGDBJUNwVl5l3OJ3Pcx+WYxfHULNcHegtw1NVWJuYVAvh4gOJYOwUZv4uyPwNFJR5LaPfVPYbMblPVy+72LrcNpIA+pB5+XfZW/ATtuMCMOKFV2twkvWF1TeLkEpV9P57NIeqz29XriPWVlsy+RVuc8ggDltxL3PE/zH3Yt0bJvFrpXD/X07Bm+0U38fy7ys1wstN0CWOJ3FCcog==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
