# roles/k3s_server/tasks/main.yml
# Install k3s, use the `k3s_cluster_init` boolean to define if it's the init node or an other node

- name: Create {{ k3s_config_dir }}
  ansible.builtin.file:
    path: "{{ k3s_config_dir }}"
    state: directory
    mode: "0755"

- name: Deploy k3s config 
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ k3s_config_dir }}/config.yaml"
    mode: "0600"
  notify: Restart k3s

- name: Download k3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /usr/local/bin/k3s-install.sh
    mode: "0755"

- name: Install k3s
  ansible.builtin.command: /usr/local/bin/k3s-install.sh server
  args:
    creates: /usr/local/bin/k3s
  environment:
    INSTALL_K3S_EXEC: server

- name: Wait k3s to be ready
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 6443
    timeout: 300

- name: Wait for node registration on the clusters
  ansible.builtin.command: k3s kubectl get node {{ k3s_node_name }}
  register: _node_registered
  until: _node_registered.rc == 0
  retries: 30
  delay: 10
  changed_when: false

- name: Wait for the node to be ready (and so, Cilium is working)
  ansible.builtin.command: >-
    k3s kubectl wait --for=condition=Ready node/{{ k3s_node_name }} --timeout=300s
  changed_when: false
  when: not k3s_cluster_init

- name: Create ~/.kube for {{ ansible_user }}
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"

- name: Copy k3s kubeconfig
  ansible.builtin.copy:
    src: "{{ k3s_config_dir }}/k3s.yaml"
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Read node-token on the init node
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: _node_token
  when: k3s_cluster_init
  no_log: true

- name: Register node-token as a fact
  ansible.builtin.set_fact:
    k3s_token: "{{ _node_token.content | b64decode | trim }}"
  when: k3s_cluster_init
  no_log: true
