# roles/disable_cstates/tasks
# Limit C-states to the first layer to avoid some CPU to crash going from idle to full load

---
- name: Add processor.max_cstate=1 to the GRUB command-line
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT="(?!.*processor\.max_cstate)[^"]*)"'
    replace: '\1 processor.max_cstate=1"'
  register: disable_cstates_grub
  notify:
    - Regenerate GRUB configuration
    - Reboot to apply the new configuration
