apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/instance: monitoring
spec:
  project: default
  sources:
    - repoURL: https://github.com/mathisDlmr/k3s-project.git
      targetRevision: main
      path: monitoring/metrics/overload-config/
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.49.0
      helm:
        valueFiles:
          - $values/monitoring/metrics/overload-config/loki-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
