apiVersion: v2
name: prometheus-custom
description: Prometheus avec configuration personnalisée
version: 1.0.0
dependencies:
  - name: prometheus
    version: 25.27.0
    repository: https://prometheus-community.github.io/helm-charts

