apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBtTGOspmOUn/d8vAUaoSlL+rXz2hb8VmDfhKBkWK/QP5csoMrsfXFeNccQh1dWVkRGFCmR5QZtAXMXd6GIGz1OGMtOGXfS7Ky9+3sbE0CRLUf/PTLoPvj9gAN0s5OdJVVHjTetf9eNwQH/ggQfbdSr/4HT4fAC1E3aTFhD1wRbUfF6pz8HpbQEhN4a7lqlNVMCkiUBdM17RbzqsYjbvFK4MCrUU/ChtEf4fvxznyeSsclnQt1LUaTN00Jbu+0/vQ/3tfsS9/Ff7LLWrtRGgQPjrWCvlZ3c3ApOBxwmYLB/3fgHOmM1wBgxam8tTaLoKnPaGU6q6yiS4wMak7IvD9RiYUZ4hMXuJK6CcbKNLlzN3ogNpMDNzvjY60HziYgDjaoCvMpyB7sJ6MlAheXkOpO6DS7Km7oYUlhsLYtpLYnfcAich1S9O8vwxr4IGAymGW0M+OqEQetxi5ySjPShaMasmSyQPaiQAuH99KeNDPXkKLZRcNdFBKxp9UJ8zwZXcR1Sq8S9en9z02YGEqryb0zxky6TKXx7FKk1EjodqfLVPYDZpg+PQE2YUIex5J0pM68oZ9UjUtDs+bQhwPqn2BwjfbA9Mu04JW+2dVDpDeM3ldqlNV22z9cn77xyr+LkUwaAZqJNOzlw9OjOStdIjZ1mVFTQJpqovimpNX4+dM4b3Dddmru1NJBTVaiBGQxwlzhUV3Usz/noaA==
    admin-user: AgBP/ZPybk4E7648MK6OFMGnDw8PNeqEk0JN5YvHnenXHJBHpbsymleLV2OTrB/5qpqGRuaDnHY+de2UgEgHGwuZrMnK/EBMG5ET3EJB0sBjSsHwFgqhVxHGU9vuq2+DrRu3P07GKudpNFoX/9zR7W2dfw8qL6IsKI9/yurvHVASigQu+DdckzcCYDSUFH1J4kaZmwA/qyJEk649vR1V1kNaHVdhFTqopJgOpe+7Y8Zjm04IeRJ/PaR/vgLGAuEJgTjgZfbyMsSh/FILpeRT3D/flTxPYe8Q3h3s4nrbvz5qACQJzjMDj5RcM2QALQZ91+MEsTXkI9MYTkEw91Kmlx2brodq+9oHzu6wVdgakCoYH+vcExDqMoi1n0CzHo7Bc16uwkz/5d1fzl0+qyOvBELXr5W+M2VIGtE2o95jCEb0awi0fxVOeCP2xg9Guck9nQDRWPb6RWAYj9MAinG2U4VB8LQMaVNy7JwyQQBOGvGq1uXymokHC4MF4iXa0XEhWFkH9vgLRRqFDR540Pc44LE4dzNMlg9Jy9IIMX1QPmYATonMiRPkTXHGqvH1yq9jaBHVvBQMVNXCDsgturSLc8ZRP9DgJRc9MdO3bRp9MfDD0VEdYXBVE6ESusmLCnMJy4qnJrDlnum2H4RS56VBdxBDKxgrrFJYaIGpW/sQzHr1mB5C4e+6idwhH+zWQTemulhplVt2mw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring

