apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgByl5BoBiKZek6jfEjQTXwg7Bg2tt0di+c9SCYGm2jLxZ+eHkQt6nzRlqdjeAumUcaU8IiFmBadGfHuurlLS2ITgZvHfYXn6sbwlbdhlZa7acJjg8sLIiImZ7vzRRefwIkJMD4xxEVuq+LNdok2ZNyI9tIqS3jFxg6Mx4EyXP2fvLKla4tbjrFZSa+fMaoXvENermB+D3ieAD4Iho04QDOS0C26l9MEIkUN3AnGOx1ko7UcA3jBMtcu+gkMP6mKwIxJR+buMCMNm+IwMcqZD1ayogOyzjKipGvE0GCqFhBtvDdTguYpVaODWrY9fLxFtKYzEDQahgzeo0VFiMDcvrIR4Pyed+wrckyTDX19zo2Y/oQfd2VE3a+PlWGKiAZb2IX/jGUiwWVD/X0SlOVFAORGnT8lj2wBFFfrwkGRHEAXHBa8j89hjLK/nW29eTGGnsu4jLPcE20zLtHae3tlRSco8DyKoGVM3nOM9fHY8HwcGYXHDCNb68zC+3jKBV8LwQ9brANpZb3pQ5DpNAa7T15C+i668TfU4JFrGnxMvMCkbewuaoUuQbiLkbN7ldo23Mff6NxQxT8DsiZiHVe1wR+luF8P7r8Sv82P1jDRFZrMsIjLTn5gSRbbeuXrk7wNHDzM6qkYHHHS7jCg7WwiFJe6+sGK3J+8+mBIakLqBzPnmicsZ1wGKqaHfyBFA9UA7Bj41QOMXWV5sIw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque

