apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-state-metrics
    targetRevision: 5.25.1
    helm:
      releaseName: kube-state-metrics
      values: |
        replicas: 1
        resources:
          limits:
            cpu: 100m
            memory: 190Mi
          requests:
            cpu: 10m
            memory: 32Mi
        serviceMonitor:
          enabled: true
        securityContext:
          enabled: true
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
