apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  source:
    repoURL: https://github.com/mathisDlmr/k3s-project.git
    path: monitoring/metrics
    targetRevision: main
    helm:
      releaseName: prometheus
      valueFiles:
        - prometheus-values.yaml
