apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.27.0
    helm:
      releaseName: prometheus
      values: |
        server:
          extraArgs:
            web.enable-lifecycle: ""

          persistentVolume:
            enabled: true
            size: 10Gi
            storageClass: "local-path"

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

          retention: "15d"
          service:
            type: ClusterIP
        
        alertmanager:
          enabled: true
          persistentVolume:
            enabled: true
            size: 2Gi
            storageClass: "local-path"
          
        nodeExporter:
          enabled: true
          
        pushgateway:
          enabled: false
          
        kubeStateMetrics:
          enabled: false
          
        # Configuration Prometheus personnalisée via ConfigMap séparé
        # La configuration par défaut de Helm sera utilisée
