apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-argocd
  namespace: meta
  labels:
    app.kubernetes.io/part-of: k3s-project
  annotations:
    description: "Application meta à la racine du projet - Elle déploie toutes les applications hebergées sur le cluster"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: meta
  source:
    repoURL: 'https://github.com/mathisDlmr/k3s-project.git'
    targetRevision: main
    path: argocd/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
