apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skiut-argocd
  namespace: skiut
  labels:
    app.kubernetes.io/part-of: k3s-project
  annotations:
    description: "Application skiut - S'occupe de l'application Ski'ut (Backend Laravel, BDD MySql, monitoring, etc.)"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: skiut
  source:
    repoURL: 'https://github.com/mathisDlmr/k3s-project.git'
    targetRevision: main
    path: apps/skiut/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
