deployment:
  kind: DaemonSet

hostNetwork: false

ports:
  web:
    port: 8000
    hostPort: 80
    expose:
      default: true
  websecure:
    port: 8443
    hostPort: 443
    expose:
      default: true

service:
  type: ClusterIP

tlsStore:
  default:
    defaultCertificate:
      secretName: mdlmr-fr-wildcard-tls

logs:
  access:
    enabled: true

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
