apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-throttling-fixed
  namespace: monitoring
  labels:
    role: alert-rules
    prometheus: monitoring-stack-kube-prom-prometheus
spec:
  groups:
    - name: kubernetes-resources-fixed
      rules:
        - alert: CPUThrottlingHighFixed
          expr: |
            (
              sum without (id, metrics_path, name, image, endpoint, job, node) (
                increase(container_cpu_cfs_throttled_periods_total{container!="",job="kubelet",metrics_path="/metrics/cadvisor"}[5m])
              )
              / on (cluster, namespace, pod, container, instance) group_left () 
              sum without (id, metrics_path, name, image, endpoint, job, node) (
                increase(container_cpu_cfs_periods_total{job="kubelet",metrics_path="/metrics/cadvisor"}[5m])
              )
            ) > (25 / 100)
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Processes experience high CPU throttling"
            description: "{{ $value | humanizePercentage }} of CPU execution time was throttled in the last 5 minutes for {{ $labels.pod }} in {{ $labels.namespace }} namespace."
