apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k3s-coredns-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: kube-dns
  endpoints:
    - port: metrics
      scheme: http
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - kube-system
  jobLabel: k8s-app
