apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k3s-cluster-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: kubelet
  endpoints:
    - port: https-metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      path: /metrics
      honorLabels: true
      relabelings:
        - sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
  namespaceSelector:
    matchNames:
      - kube-system
  jobLabel: k8s-app
