apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k3s-kube-proxy-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/name: k3s-kube-proxy-monitor
    app.kubernetes.io/component: servicemonitor
  annotations:
    description: "ServiceMonitor pour surveiller kube-proxy dans k3s"
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  endpoints:
  - port: http-metrics
    scheme: http
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - kube-system
  jobLabel: k8s-app
