apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: skiut-mysql-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: skiut-database
  endpoints:
    - port: mysql
      scheme: http
      interval: 30s
      path: /metrics
      honorLabels: true
  namespaceSelector:
    matchNames:
      - skiut
  jobLabel: app
