apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflared-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /cloudflare/CLOUDFLARE_TUNNEL_TOKEN
