apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-auth
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: longhorn-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: /longhorn/LONGHORN_HTPASSWD
