apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack
  namespace: monitoring
type: Opaque
data:
  webhook: BASE64_ENCODED_HOOK   # webhook (base64)

---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  namespace: monitoring
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['job']
    receiver: 'slack'
  receivers:
    - name: 'slack'
      slackConfigs:
        - apiURL:
            name: alertmanager-slack
            key: webhook
          channel: "#alerts"
