apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: infra
spec:
  encryptedData:
    api-token: AgAmgWbHWOBB44MrRoZWfNNDyxEb0F0h7RiprNjx8Mq4eoK4ByzxkqEolibYcNL1NG7jo0ZTEm+aPR2BvMTt+UNX1IGVmwjY8DpxR6LdMj+XgkNxuW6iun1x0ctuYE6eisXmbyZJTnDuNoEOe0CrFqiCGCEOMw1T7w/X4uY/rs7KERHFLB1xEEiw/BztTwK8g8//pQDuzVLhcLWjQNmo7nanm0HCDyeQnp7qPHh9wBNfH58fXdecQit3h701VoWeqyK+Vs66SAdMuWh0qmLkrj4a/1mb7g6MBpeaHfsuMgkqf18TOv/4C1s3I1ofuCsdXiUCd7rJ15x/f3hfLt8Q0yfEMZGq97+HT9qeH3a4j1RvH+QGHDmuMs8ZJ9d20JYaSnRzxUandc8k4hxB5mVxIJd4MCjowLBKV2enwCuGTt0X1JCF2369+xaE/z5FGuuzXUywr6ZUgyM0Jgvhcp59DNvcjEBovsyXOli+73XbrE2u8JFjjmhwUsSF1+F8Wm65kBKHtgr5B1aOvN0rDu3mhXUzS0OGLJa/D3m4oV2AChj54lUcl+ZAy/vTBQrWolcc9NAMjruzppO1l6orgp/WEcqvYQ8RfqURAt2nVJfTHkz8ITRK+UcSdpGpNo2FpYVxieLpNwjZ8/AN45jge0NQ/rgnVWUzvzeSy5ByNlmUwyVXMMPT9SoCp1LLTq4p115Q+ZO1j51gCdyrkzOsZ9kv3xEyBChtlvvKfUzTOhgXBGAaeom4l+g97Iyi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: infra
    type: Opaque

