apiVersion: v1
kind: ConfigMap
metadata:
  name: skiut-proxysql-config
  namespace: skiut
  labels:
    app: skiut-proxysql
    app.kubernetes.io/name: skiut-proxysql
    app.kubernetes.io/component: config
  annotations:
    description: "Configuration ProxySQL pour l'application skiut"
data:
  entrypoint.sh: |
    #!/bin/sh
    set -e

    cat > /etc/proxysql.cnf <<EOF
    datadir="/var/lib/proxysql"
    
    admin_variables =
    {
        admin_credentials="admin:${MYSQL_PROXY_ADMIN_PASSWORD}"
        mysql_ifaces="0.0.0.0:603"
        refresh_interval=2000
        debug=false
    }
    
    mysql_servers =
    (
        {
            address="skiut-database-service"
            port="3306"
            hostgroup=0
            max_connections=200
            max_replication_lag=10
            use_ssl=0
        }
    )
    
    mysql_users =
    (
        {
            username="admin"
            password="${MYSQL_PROXY_ADMIN_PASSWORD}"
            default_hostgroup=0
            active=1
        },
        {
            username="${MYSQL_USER}"
            password="${MYSQL_PASSWORD}"
            default_hostgroup=0
            active=1
        }
    )

    mysql_variables =
    {
        threads=2
        max_connections=1000
        connection_max_age_ms=300000
        wait_timeout=300000
    }
    
    mysql_query_rules = ()
    EOF

    exec proxysql -f -c /etc/proxysql.cnf