apiVersion: v1
kind: Secret
metadata:
  name: skiut-database-secret
  namespace: skiut
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # rootpassword
  MYSQL_USER: c2tpdXR1c2Vy  # skiutuser
  MYSQL_PASSWORD: c2tpdXRwYXNzd29yZA==  # skiutpassword
