apiVersion: batch/v1
kind: CronJob
metadata:
  name: skiut-permanence-reminder-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: scheduler
              image: ghcr.io/ski-utc/server-skiut-2026:17df64d915544f54057e7738a45fb6bebd34b97d
              command: ["php", "artisan", "permanence:send-reminders"]
              volumeMounts:
                - name: laravel-storage
                  mountPath: /var/www/html/storage
              env:
                - name: LOG_CHANNEL
                  value: stderr
                - name: APP_ENV
                  value: production
                - name: APP_URL
                  value: https://skiut.mdlmr.fr
                - name: DB_CONNECTION
                  value: mysql
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-database-configmap
                      key: MYSQL_HOST
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-database-configmap
                      key: MYSQL_PORT
                - name: DB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-database-configmap
                      key: MYSQL_DB
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: skiut-database-secret
                      key: MYSQL_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: skiut-database-secret
                      key: MYSQL_PASSWORD
                - name: SIMDE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: skiut-backend-secret
                      key: SIMDE_KEY
                - name: OAUTH_REDIRECT_URI
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-backend-configmap
                      key: OAUTH_REDIRECT_URI
                - name: OAUTH_BACKOFFICE_REDIRECT_URI
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-backend-configmap
                      key: OAUTH_BACKOFFICE_REDIRECT_URI
                - name: OAUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: skiut-backend-secret
                      key: OAUTH_CLIENT_ID
                - name: OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: skiut-backend-secret
                      key: OAUTH_CLIENT_SECRET
          restartPolicy: Never
          volumes:
            - name: laravel-storage
              persistentVolumeClaim:
                claimName: skiut-backend-storage
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skiut-meeting-reminder-cronjob
spec:
  schedule: "30 19 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: scheduler
              image: ghcr.io/ski-utc/server-skiut-2026:83f25ab91e464afadaace5fe102068cd468827d1
              command:
                [
                  "php",
                  "artisan",
                  "notification:send-to-members --title='Réunion Asso dans 30 minutes !' --text='Rendez-vous en chambre 166 à 20h pour la réunion asso'",
                ]
              volumeMounts:
                - name: laravel-storage
                  mountPath: /var/www/html/storage
              env:
                - name: LOG_CHANNEL
                  value: stderr
                - name: APP_ENV
                  value: production
                - name: APP_URL
                  value: https://skiut.mdlmr.fr
                - name: DB_CONNECTION
                  value: mysql
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-database-configmap
                      key: MYSQL_HOST
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-database-configmap
                      key: MYSQL_PORT
                - name: DB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-database-configmap
                      key: MYSQL_DB
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: skiut-database-secret
                      key: MYSQL_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: skiut-database-secret
                      key: MYSQL_PASSWORD
                - name: SIMDE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: skiut-backend-secret
                      key: SIMDE_KEY
                - name: OAUTH_REDIRECT_URI
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-backend-configmap
                      key: OAUTH_REDIRECT_URI
                - name: OAUTH_BACKOFFICE_REDIRECT_URI
                  valueFrom:
                    configMapKeyRef:
                      name: skiut-backend-configmap
                      key: OAUTH_BACKOFFICE_REDIRECT_URI
                - name: OAUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: skiut-backend-secret
                      key: OAUTH_CLIENT_ID
                - name: OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: skiut-backend-secret
                      key: OAUTH_CLIENT_SECRET
          restartPolicy: Never
          volumes:
            - name: laravel-storage
              persistentVolumeClaim:
                claimName: skiut-backend-storage
