apiVersion: v1
kind: PersistentVolume
metadata:
  name: skiut-stable-pv
  labels:
    app: skiut
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "skiut"
  local:
    path: /var/skiut-stable-pv
