---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-platform-pull-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: media-platform-pull-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:mathisdlmr/media-platform.git
        sshPrivateKey: "{{ .ssh_private_key }}"
  data:
    - secretKey: ssh_private_key
      remoteRef:
        key: /personnal/media-platform/ARGOCD_SSH_PRIVATE_KEY