---
name: Ansible Checkups

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible-checkups.yaml"
  pull_request:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible-checkups.yaml"

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14.6"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint
          ansible-galaxy collection install -r ansible/requirements.yml

      - name: Run Ansible Lint
        working-directory: ansible
        run: |
          ansible-lint .

  molecule-test:
    name: Molecule Test roles
    needs: ansible-lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
          - argocd_bootstrap
          - cilium
          - common
          - k3s_server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14.6"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-plugins[docker] pytest pytest-testinfra

      - name: Test role ${{ matrix.role }}
        working-directory: ansible/roles/${{ matrix.role }}
        run: molecule test
