---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eck-operator-pod-monitor
spec:
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 1m
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames: [monitoring-v2]
  selector:
    matchLabels:
      app.kubernetes.io/name: elastic-operator
